name: Daily Heartbeat Commit

on:
  schedule:
    # DAILY at 15:13 UTC — change to your preferred time (UTC).
    - cron: "13 15 * * *"
  workflow_dispatch:

# Let this workflow push to THIS repo using the built-in GITHUB_TOKEN.
permissions:
  contents: write

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          # Uses GITHUB_TOKEN so we can push back to the same repo/branch.
          persist-credentials: true

      - name: Configure git identity
        run: |
          git config user.name  "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Append heartbeat
        run: |
          mkdir -p .github
          FILE=".github/heartbeat.md"
          echo "$(date -u +'%Y-%m-%d %H:%M:%S UTC') — automated heartbeat" >> "$FILE"
          git add "$FILE"
          git commit -m "chore: heartbeat [skip ci] ($(date -u +'%Y-%m-%d'))" || echo "Nothing to commit."

      - name: Push (if a commit exists)
        run: |
          if git log -1 --pretty=%B | grep -q 'heartbeat'; then
            # Push back to the same branch we checked out (usually default branch)
            CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
            git push origin "$CURRENT_BRANCH"

            SHA="$(git rev-parse HEAD)"
            echo "### Repo: $GITHUB_REPOSITORY" >> "$GITHUB_STEP_SUMMARY"
            echo "### Branch: $CURRENT_BRANCH" >> "$GITHUB_STEP_SUMMARY"
            echo "### Commit: [$SHA](https://github.com/$GITHUB_REPOSITORY/commit/$SHA)" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "### No changes detected; skipping push." >> "$GITHUB_STEP_SUMMARY"
          fi
